/*
 * Created on 2019-05-04 ( Date ISO 2019-05-04 - Time 23:46:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc;

import org.demo.data.record.InvoiceRecord;
import org.demo.persistence.InvoicePersistence;
import org.demo.persistence.impl.jdbc.commons.GenericJdbcDAO;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * Invoice persistence implementation
 *
 * @author Telosys
 */

public class InvoicePersistenceJdbc extends GenericJdbcDAO<InvoiceRecord>
    implements InvoicePersistence {

  private static final String SQL_SELECT_ALL = "select id, user, payment, paid from invoice";

  private static final String SQL_SELECT =
      "select id, user, payment, paid from invoice where id = ?";

  private static final String SQL_INSERT =
      "insert into invoice ( user, payment, paid ) values ( ?, ?, ? )";

  private static final String SQL_UPDATE =
      "update invoice set user = ?, payment = ?, paid = ? where id = ?";

  private static final String SQL_DELETE = "delete from invoice where id = ?";

  private static final String SQL_COUNT_ALL = "select count(*) from invoice";

  private static final String SQL_COUNT = "select count(*) from invoice where id = ?";

  // ----------------------------------------------------------------------
  /** DAO constructor */
  public InvoicePersistenceJdbc() {
    super();
  }

  // ----------------------------------------------------------------------
  @Override
  protected void setAutoIncrementedKey(InvoiceRecord record, long value) {
    record.setId((Integer) (int)value);
  }

  // ----------------------------------------------------------------------
  @Override
  protected void setValuesForPrimaryKey(PreparedStatement ps, int i, InvoiceRecord invoice)
      throws SQLException {
    // --- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
    setValue(ps, i++, invoice.getId()); // "id" : java.lang.Integer
  }

  // ----------------------------------------------------------------------
  @Override
  protected void setValuesForInsert(PreparedStatement ps, int i, InvoiceRecord invoice)
      throws SQLException {
    // --- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
    // "id" is auto-incremented => no set in insert
    setValue(ps, i++, invoice.getUser()); // "user" : java.lang.Integer
    setValue(ps, i++, invoice.getPayment()); // "payment" : java.lang.Long
    setValue(ps, i++, invoice.getPaid()); // "paid" : java.lang.Byte
  }

  // ----------------------------------------------------------------------
  @Override
  protected void setValuesForUpdate(PreparedStatement ps, int i, InvoiceRecord invoice)
      throws SQLException {
    // --- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
    setValue(ps, i++, invoice.getUser()); // "user" : java.lang.Integer
    setValue(ps, i++, invoice.getPayment()); // "payment" : java.lang.Long
    setValue(ps, i++, invoice.getPaid()); // "paid" : java.lang.Byte
    // --- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
    setValue(ps, i++, invoice.getId()); // "id" : java.lang.Integer
  }

  // ----------------------------------------------------------------------
  /**
   * Creates a new instance of the bean and populates it with the given primary value(s)
   *
   * @param id;
   * @return the new instance
   */
  private InvoiceRecord newInstanceWithPrimaryKey(Integer id) {
    InvoiceRecord invoice = new InvoiceRecord();
    invoice.setId(id);
    return invoice;
  }

  // ----------------------------------------------------------------------
  @Override
  protected InvoiceRecord newInstance() {
    return new InvoiceRecord();
  }

  // ----------------------------------------------------------------------
  @Override
  protected InvoiceRecord populateBean(ResultSet rs, InvoiceRecord invoice) throws SQLException {

    // --- Set data from ResultSet to Bean attributes
    invoice.setId(rs.getInt("id")); // java.lang.Integer
    if (rs.wasNull()) {
      invoice.setId(null);
    }
      // not primitive number => keep null value if any
    invoice.setUser(rs.getInt("user")); // java.lang.Integer
    if (rs.wasNull()) {
      invoice.setUser(null);
    }
      // not primitive number => keep null value if any
    invoice.setPayment(rs.getLong("payment")); // java.lang.Long
    if (rs.wasNull()) {
      invoice.setPayment(null);
    }
      // not primitive number => keep null value if any
    invoice.setPaid(rs.getByte("paid")); // java.lang.Byte
    if (rs.wasNull()) {
      invoice.setPaid(null);
    }
      // not primitive number => keep null value if any
    return invoice;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public InvoiceRecord findById(Integer id) {
    InvoiceRecord invoice = newInstanceWithPrimaryKey(id);
    if (super.doSelect(invoice)) {
      return invoice;
    } else {
      return null; // Not found
    }
  }
  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public List<InvoiceRecord> findAll() {
    return super.doSelectAll();
  }

  // ----------------------------------------------------------------------
  /**
   * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)
   * <br>
   * If found, the given instance is populated with the values retrieved from the database<br>
   * If not found, the given instance remains unchanged
   *
   * @param invoice
   * @return true if found, false if not found
   */
  // @Override
  public boolean load(InvoiceRecord invoice) {
    return super.doSelect(invoice);
  }

  // ----------------------------------------------------------------------
  /**
   * Inserts the given bean in the database
   *
   * @param invoice
   */
  public long insert(InvoiceRecord invoice) {
    Long key = super.doInsertAutoIncr(invoice);
    return key.longValue();
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public InvoiceRecord create(InvoiceRecord invoice) {
    insert(invoice);
    return invoice;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public boolean update(InvoiceRecord invoice) {
    int r = super.doUpdate(invoice);
    return r > 0;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public InvoiceRecord save(InvoiceRecord invoice) {
    if (super.doExists(invoice)) {
      super.doUpdate(invoice);
    } else {
      super.doInsert(invoice);
    }
    return invoice;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public boolean deleteById(Integer id) {
    InvoiceRecord invoice = newInstanceWithPrimaryKey(id);
    int r = super.doDelete(invoice);
    return r > 0;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public boolean delete(InvoiceRecord invoice) {
    int r = super.doDelete(invoice);
    return r > 0;
  }

  // ----------------------------------------------------------------------
  /**
   * Checks the existence of a record in the database using the given primary key value(s)
   *
   * @param id;
   * @return
   */
  // @Override
  public boolean exists(Integer id) {
    InvoiceRecord invoice = newInstanceWithPrimaryKey(id);
    return super.doExists(invoice);
  }
  // ----------------------------------------------------------------------
  /**
   * Checks the existence of the given bean in the database
   *
   * @param invoice
   * @return
   */
  // @Override
  public boolean exists(InvoiceRecord invoice) {
    return super.doExists(invoice);
  }

  // ----------------------------------------------------------------------
  /**
   * Counts all the records present in the database
   *
   * @return
   */
  @Override
  public long countAll() {
    return super.doCountAll();
  }

  // ----------------------------------------------------------------------
  @Override
  protected String getSqlSelect() {
    return SQL_SELECT;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlSelectAll() {
    return SQL_SELECT_ALL;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlInsert() {
    return SQL_INSERT;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlUpdate() {
    return SQL_UPDATE;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlDelete() {
    return SQL_DELETE;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlCount() {
    return SQL_COUNT;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlCountAll() {
    return SQL_COUNT_ALL;
  }
}
