/*
 * Created on 2019-05-04 ( Date ISO 2019-05-04 - Time 23:46:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc;

import org.demo.data.record.SubscriptionRecord;
import org.demo.persistence.SubscriptionPersistence;
import org.demo.persistence.impl.jdbc.commons.GenericJdbcDAO;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * Subscription persistence implementation
 *
 * @author Telosys
 */

public class SubscriptionPersistenceJdbc extends GenericJdbcDAO<SubscriptionRecord>
    implements SubscriptionPersistence {

  private static final String SQL_SELECT_ALL =
      "select id, user, periodical, invoice, expires from subscription";

  private static final String SQL_SELECT =
      "select id, user, periodical, invoice, expires from subscription where id = ?";

  private static final String SQL_INSERT =
      "insert into subscription ( user, periodical, invoice, expires ) values ( ?, ?, ?, ? )";

  private static final String SQL_UPDATE =
      "update subscription set user = ?, periodical = ?, invoice = ?, expires = ? where id = ?";

  private static final String SQL_DELETE = "delete from subscription where id = ?";

  private static final String SQL_COUNT_ALL = "select count(*) from subscription";

  private static final String SQL_COUNT = "select count(*) from subscription where id = ?";

  // ----------------------------------------------------------------------
  /** DAO constructor */
  public SubscriptionPersistenceJdbc() {
    super();
  }

  // ----------------------------------------------------------------------
  @Override
  protected void setAutoIncrementedKey(SubscriptionRecord record, long value) {
    record.setId((Integer) (int)value);
  }

  // ----------------------------------------------------------------------
  @Override
  protected void setValuesForPrimaryKey(
      PreparedStatement ps, int i, SubscriptionRecord subscription) throws SQLException {
    // --- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
    setValue(ps, i++, subscription.getId()); // "id" : java.lang.Integer
  }

  // ----------------------------------------------------------------------
  @Override
  protected void setValuesForInsert(PreparedStatement ps, int i, SubscriptionRecord subscription)
      throws SQLException {
    // --- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
    // "id" is auto-incremented => no set in insert
    setValue(ps, i++, subscription.getUser()); // "user" : java.lang.Integer
    setValue(ps, i++, subscription.getPeriodical()); // "periodical" : java.lang.Integer
    setValue(ps, i++, subscription.getInvoice()); // "invoice" : java.lang.Integer
    setValue(ps, i++, subscription.getExpires()); // "expires" : java.util.Date
  }

  // ----------------------------------------------------------------------
  @Override
  protected void setValuesForUpdate(PreparedStatement ps, int i, SubscriptionRecord subscription)
      throws SQLException {
    // --- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
    setValue(ps, i++, subscription.getUser()); // "user" : java.lang.Integer
    setValue(ps, i++, subscription.getPeriodical()); // "periodical" : java.lang.Integer
    setValue(ps, i++, subscription.getInvoice()); // "invoice" : java.lang.Integer
    setValue(ps, i++, subscription.getExpires()); // "expires" : java.util.Date
    // --- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
    setValue(ps, i++, subscription.getId()); // "id" : java.lang.Integer
  }

  // ----------------------------------------------------------------------
  /**
   * Creates a new instance of the bean and populates it with the given primary value(s)
   *
   * @param id;
   * @return the new instance
   */
  private SubscriptionRecord newInstanceWithPrimaryKey(Integer id) {
    SubscriptionRecord subscription = new SubscriptionRecord();
    subscription.setId(id);
    return subscription;
  }

  // ----------------------------------------------------------------------
  @Override
  protected SubscriptionRecord newInstance() {
    return new SubscriptionRecord();
  }

  // ----------------------------------------------------------------------
  @Override
  protected SubscriptionRecord populateBean(ResultSet rs, SubscriptionRecord subscription)
      throws SQLException {

    // --- Set data from ResultSet to Bean attributes
    subscription.setId(rs.getInt("id")); // java.lang.Integer
    if (rs.wasNull()) {
      subscription.setId(null);
    }
      // not primitive number => keep null value if any
    subscription.setUser(rs.getInt("user")); // java.lang.Integer
    if (rs.wasNull()) {
      subscription.setUser(null);
    }
      // not primitive number => keep null value if any
    subscription.setPeriodical(rs.getInt("periodical")); // java.lang.Integer
    if (rs.wasNull()) {
      subscription.setPeriodical(null);
    }
      // not primitive number => keep null value if any
    subscription.setInvoice(rs.getInt("invoice")); // java.lang.Integer
    if (rs.wasNull()) {
      subscription.setInvoice(null);
    }
      // not primitive number => keep null value if any
    subscription.setExpires(rs.getDate("expires")); // java.util.Date
    return subscription;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public SubscriptionRecord findById(Integer id) {
    SubscriptionRecord subscription = newInstanceWithPrimaryKey(id);
    if (super.doSelect(subscription)) {
      return subscription;
    } else {
      return null; // Not found
    }
  }
  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public List<SubscriptionRecord> findAll() {
    return super.doSelectAll();
  }

  // ----------------------------------------------------------------------
  /**
   * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)
   * <br>
   * If found, the given instance is populated with the values retrieved from the database<br>
   * If not found, the given instance remains unchanged
   *
   * @param subscription
   * @return true if found, false if not found
   */
  // @Override
  public boolean load(SubscriptionRecord subscription) {
    return super.doSelect(subscription);
  }

  // ----------------------------------------------------------------------
  /**
   * Inserts the given bean in the database
   *
   * @param subscription
   */
  public long insert(SubscriptionRecord subscription) {
    Long key = super.doInsertAutoIncr(subscription);
    return key.longValue();
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public SubscriptionRecord create(SubscriptionRecord subscription) {
    insert(subscription);
    return subscription;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public boolean update(SubscriptionRecord subscription) {
    int r = super.doUpdate(subscription);
    return r > 0;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public SubscriptionRecord save(SubscriptionRecord subscription) {
    if (super.doExists(subscription)) {
      super.doUpdate(subscription);
    } else {
      super.doInsert(subscription);
    }
    return subscription;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public boolean deleteById(Integer id) {
    SubscriptionRecord subscription = newInstanceWithPrimaryKey(id);
    int r = super.doDelete(subscription);
    return r > 0;
  }

  // ----------------------------------------------------------------------
  /* (non-Javadoc)
   * @see interface
   */
  @Override
  public boolean delete(SubscriptionRecord subscription) {
    int r = super.doDelete(subscription);
    return r > 0;
  }

  // ----------------------------------------------------------------------
  /**
   * Checks the existence of a record in the database using the given primary key value(s)
   *
   * @param id;
   * @return
   */
  // @Override
  public boolean exists(Integer id) {
    SubscriptionRecord subscription = newInstanceWithPrimaryKey(id);
    return super.doExists(subscription);
  }
  // ----------------------------------------------------------------------
  /**
   * Checks the existence of the given bean in the database
   *
   * @param subscription
   * @return
   */
  // @Override
  public boolean exists(SubscriptionRecord subscription) {
    return super.doExists(subscription);
  }

  // ----------------------------------------------------------------------
  /**
   * Counts all the records present in the database
   *
   * @return
   */
  @Override
  public long countAll() {
    return super.doCountAll();
  }

  // ----------------------------------------------------------------------
  @Override
  protected String getSqlSelect() {
    return SQL_SELECT;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlSelectAll() {
    return SQL_SELECT_ALL;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlInsert() {
    return SQL_INSERT;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlUpdate() {
    return SQL_UPDATE;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlDelete() {
    return SQL_DELETE;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlCount() {
    return SQL_COUNT;
  }
  // ----------------------------------------------------------------------
  @Override
  protected String getSqlCountAll() {
    return SQL_COUNT_ALL;
  }
}
