/*
 * Created on 2019-05-04 ( Date ISO 2019-05-04 - Time 23:47:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;

import java.io.Serializable;

/**
 * Java bean for entity "periodical" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 *
 * @author Telosys Tools Generator
 */
public class PeriodicalRecord implements Serializable {
  private static final long serialVersionUID = 1L;

  private Integer id; // Integer // Id or Primary Key

  private Integer category; // Integer

  private String title; // String

  private Integer price; // Integer

  /** Default constructor */
  public PeriodicalRecord() {
    super();
  }

  // ----------------------------------------------------------------------
  // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY
  // ----------------------------------------------------------------------

  /**
   * Get the "id" field value This field is mapped on the database column "id" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @return the field value
   */
  public Integer getId() {
    return this.id;
  }

  /**
   * Set the "id" field value This field is mapped on the database column "id" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @param id
   */
  public void setId(Integer id) {
    this.id = id;
  }

  // ----------------------------------------------------------------------
  // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
  // ----------------------------------------------------------------------

  /**
   * Get the "category" field value This field is mapped on the database column "category" ( type
   * "INT UNSIGNED", NotNull : true )
   *
   * @return the field value
   */
  public Integer getCategory() {
    return this.category;
  }

  /**
   * Set the "category" field value This field is mapped on the database column "category" ( type
   * "INT UNSIGNED", NotNull : true )
   *
   * @param category
   */
  public void setCategory(Integer category) {
    this.category = category;
  }

  /**
   * Get the "title" field value This field is mapped on the database column "title" ( type
   * "TINYTEXT", NotNull : true )
   *
   * @return the field value
   */
  public String getTitle() {
    return this.title;
  }

  /**
   * Set the "title" field value This field is mapped on the database column "title" ( type
   * "TINYTEXT", NotNull : true )
   *
   * @param title
   */
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * Get the "price" field value This field is mapped on the database column "price" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @return the field value
   */
  public Integer getPrice() {
    return this.price;
  }

  /**
   * Set the "price" field value This field is mapped on the database column "price" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @param price
   */
  public void setPrice(Integer price) {
    this.price = price;
  }

  // ----------------------------------------------------------------------
  // toString METHOD
  // ----------------------------------------------------------------------
  @Override
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append(id);
    sb.append("|");
    sb.append(category);
    sb.append("|");
    sb.append(title);
    sb.append("|");
    sb.append(price);
    return sb.toString();
  }
}
