/*
 * Created on 2019-05-04 ( Date ISO 2019-05-04 - Time 23:47:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for entity "subscription" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 *
 * @author Telosys Tools Generator
 */
public class SubscriptionRecord implements Serializable {
  private static final long serialVersionUID = 1L;

  private Integer id; // Integer // Id or Primary Key

  private Integer user; // Integer
  private Integer periodical; // Integer
  private Integer invoice; // Integer
  private Date expires; // Date

  /** Default constructor */
  public SubscriptionRecord() {
    super();
  }

  // ----------------------------------------------------------------------
  // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY
  // ----------------------------------------------------------------------

  /**
   * Get the "id" field value This field is mapped on the database column "id" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @return the field value
   */
  public Integer getId() {
    return this.id;
  }

  /**
   * Set the "id" field value This field is mapped on the database column "id" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @param id
   */
  public void setId(Integer id) {
    this.id = id;
  }

  // ----------------------------------------------------------------------
  // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
  // ----------------------------------------------------------------------

  /**
   * Get the "user" field value This field is mapped on the database column "user" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @return the field value
   */
  public Integer getUser() {
    return this.user;
  }

  /**
   * Set the "user" field value This field is mapped on the database column "user" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @param user
   */
  public void setUser(Integer user) {
    this.user = user;
  }

  /**
   * Get the "periodical" field value This field is mapped on the database column "periodical" (
   * type "INT UNSIGNED", NotNull : true )
   *
   * @return the field value
   */
  public Integer getPeriodical() {
    return this.periodical;
  }

  /**
   * Set the "periodical" field value This field is mapped on the database column "periodical" (
   * type "INT UNSIGNED", NotNull : true )
   *
   * @param periodical
   */
  public void setPeriodical(Integer periodical) {
    this.periodical = periodical;
  }

  /**
   * Get the "invoice" field value This field is mapped on the database column "invoice" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @return the field value
   */
  public Integer getInvoice() {
    return this.invoice;
  }

  /**
   * Set the "invoice" field value This field is mapped on the database column "invoice" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @param invoice
   */
  public void setInvoice(Integer invoice) {
    this.invoice = invoice;
  }

  /**
   * Get the "expires" field value This field is mapped on the database column "expires" ( type
   * "DATE", NotNull : true )
   *
   * @return the field value
   */
  public Date getExpires() {
    return this.expires;
  }

  /**
   * Set the "expires" field value This field is mapped on the database column "expires" ( type
   * "DATE", NotNull : true )
   *
   * @param expires
   */
  public void setExpires(Date expires) {
    this.expires = expires;
  }

  // ----------------------------------------------------------------------
  // toString METHOD
  // ----------------------------------------------------------------------
  @Override
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append(id);
    sb.append("|");
    sb.append(user);
    sb.append("|");
    sb.append(periodical);
    sb.append("|");
    sb.append(invoice);
    sb.append("|");
    sb.append(expires);
    return sb.toString();
  }
}
