/*
 * Created on 2019-05-04 ( Date ISO 2019-05-04 - Time 23:47:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;

import java.io.Serializable;

/**
 * Java bean for entity "user" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 *
 * @author Telosys Tools Generator
 */
public class UserRecord implements Serializable {
  private static final long serialVersionUID = 1L;

  private Integer id; // Integer // Id or Primary Key

  private String name; // String

  private String email; // String

  private String password; // String

  private String role; // String

  /** Default constructor */
  public UserRecord() {
    super();
  }

  // ----------------------------------------------------------------------
  // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY
  // ----------------------------------------------------------------------

  /**
   * Get the "id" field value This field is mapped on the database column "id" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @return the field value
   */
  public Integer getId() {
    return this.id;
  }

  /**
   * Set the "id" field value This field is mapped on the database column "id" ( type "INT
   * UNSIGNED", NotNull : true )
   *
   * @param id
   */
  public void setId(Integer id) {
    this.id = id;
  }

  // ----------------------------------------------------------------------
  // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
  // ----------------------------------------------------------------------

  /**
   * Get the "name" field value This field is mapped on the database column "name" ( type
   * "TINYTEXT", NotNull : true )
   *
   * @return the field value
   */
  public String getName() {
    return this.name;
  }

  /**
   * Set the "name" field value This field is mapped on the database column "name" ( type
   * "TINYTEXT", NotNull : true )
   *
   * @param name
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Get the "email" field value This field is mapped on the database column "email" ( type
   * "VARCHAR", NotNull : true )
   *
   * @return the field value
   */
  public String getEmail() {
    return this.email;
  }

  /**
   * Set the "email" field value This field is mapped on the database column "email" ( type
   * "VARCHAR", NotNull : true )
   *
   * @param email
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * Get the "password" field value This field is mapped on the database column "password" ( type
   * "VARCHAR", NotNull : true )
   *
   * @return the field value
   */
  public String getPassword() {
    return this.password;
  }

  /**
   * Set the "password" field value This field is mapped on the database column "password" ( type
   * "VARCHAR", NotNull : true )
   *
   * @param password
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * Get the "role" field value This field is mapped on the database column "role" ( type "ENUM",
   * NotNull : true )
   *
   * @return the field value
   */
  public String getRole() {
    return this.role;
  }

  /**
   * Set the "role" field value This field is mapped on the database column "role" ( type "ENUM",
   * NotNull : true )
   *
   * @param role
   */
  public void setRole(String role) {
    this.role = role;
  }

  // ----------------------------------------------------------------------
  // toString METHOD
  // ----------------------------------------------------------------------
  @Override
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append(id);
    sb.append("|");
    sb.append(name);
    sb.append("|");
    sb.append(email);
    sb.append("|");
    sb.append(password);
    sb.append("|");
    sb.append(role);
    return sb.toString();
  }
}
